version: "2.1"

dependencies: ./project-dependencies.yaml

default:
  build-command:
    current: |
      xmlstarlet ed --inplace --omit-decl --ps -N pom="http://maven.apache.org/POM/4.0.0" --delete '/pom:project/pom:modules/pom:module' pom.xml
      mvn -e clean install
    upstream: |
      xmlstarlet ed --inplace --omit-decl --ps -N pom="http://maven.apache.org/POM/4.0.0" --delete '/pom:project/pom:modules/pom:module' pom.xml
      cat pom.xml
      mvn -e -T1C clean install -Dproguard=off -DskipTests
    after:
      upstream: rm -rf ./*
