version: "2.1"

dependencies: ./project-dependencies.yaml

default:
  build-command:
    current: |
      mvn -e clean install
    upstream: |
      mvn versions:set-property -Dproperty=libthrift.version -DnewVersion=$(thrift --version | awk '{print $3}')
      mvn versions:set-property -Dproperty=protobuf.version -DnewVersion=$(protoc --version | awk '{print $2}')
      mvn -e -T1C clean install -DskipTests
    after:
      upstream: rm -rf ./*
