version: "2.1"

dependencies: ./project-dependencies.yaml

default:
  build-command:
    current: |
      mvn -e clean install
    upstream: |
      mvn versions:set-property -Dproperty=libthrift.version -DnewVersion=$(thrift --version | awk '{print $3}')
      mvn versions:set-property -Dproperty=protobuf.version -DnewVersion=$(protoc --version | awk '{print $2}')
      xmlstarlet ed --inplace --omit-decl --ps -N pom="http://maven.apache.org/POM/4.0.0" --delete '/pom:project/pom:modules' pom.xml
      cat pom.xml
      mvn -e -T1C clean install -Dproguard=off -DskipTests
    after:
      upstream: rm -rf ./*
